<?php

namespace Models;

use CoffeeCode\DataLayer\DataLayer;

class User extends DataLayer
{
    public function __construct()
    {
        parent::__construct("users", ["first_name", "last_name"], "id", true);
    }

    public function addresses(){
        return (new Address())->$this->find("user_id = :uid", "uid={$this->id}")->fetch(true);
    }

    public function save(): bool
    {
        // verify mail
        return parent::save(); // TODO: Change the autogenerated stub
    }
}